server:
  port: 8080  # Hotels service port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_booking_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Disable Eureka completely
eureka:
  client:
    enabled: false
  instance:
    enabled: false

# Optional: Logging
logging:
  level:
    org.springframework: INFO
